# Generated by Django 5.0.4 on 2026-03-20 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0005_product_beneficios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador URL. Se usa en el endpoint de webhook.', unique=True, verbose_name='Slug')),
                ('tipo_integracion', models.CharField(choices=[('api_rest', 'API REST'), ('webhook', 'Solo webhooks'), ('csv', 'Archivo CSV'), ('manual', 'Manual')], default='api_rest', max_length=20, verbose_name='Tipo de integración')),
                ('endpoint_base', models.URLField(blank=True, help_text='URL raíz de la API del proveedor (ej: https://api.proveedor.com/v1)', verbose_name='Endpoint base')),
                ('_credenciales', models.TextField(blank=True, db_column='credenciales', help_text='JSON cifrado. Usar el campo "credenciales" del formulario.')),
                ('webhook_secret', models.CharField(blank=True, help_text='Clave HMAC para validar la firma de webhooks entrantes.', max_length=256, verbose_name='Secreto del webhook')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('prueba', 'En prueba'), ('error', 'Error de conexión')], default='activo', max_length=20, verbose_name='Estado')),
                ('politica_precios', models.JSONField(default=dict, help_text='Define cómo calcular el precio final. Ejemplos: {"tipo": "margen", "valor": 0.30} — sube el precio 30 %; {"tipo": "multiplicador", "valor": 1.5}; {"tipo": "fijo", "valor": 5000} — agrega $5.000 fijos.', verbose_name='Política de precios')),
                ('moneda_origen', models.CharField(default='COP', max_length=3, verbose_name='Moneda origen')),
                ('buffer_stock', models.IntegerField(default=0, help_text='Unidades a descontar del stock reportado (ej: 2 → si proveedor dice 10, se guarda 8).', verbose_name='Buffer de stock')),
                ('tiempo_entrega_dias', models.PositiveIntegerField(default=3, verbose_name='Tiempo de entrega (días)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor_product_id', models.CharField(max_length=200, verbose_name='ID en el proveedor')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, max_length=200, verbose_name='Categoría del proveedor')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('sincronizando', 'Sincronizando'), ('error', 'Error de sincronización')], default='activo', max_length=20, verbose_name='Estado')),
                ('datos_raw', models.JSONField(default=dict, help_text='Payload exacto recibido del proveedor. Solo lectura — no editar manualmente.', verbose_name='Datos originales')),
                ('fecha_sync', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto_local', models.ForeignKey(blank=True, help_text='Producto del catálogo propio al que pertenece este registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes_proveedor', to='products.product', verbose_name='Producto local vinculado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto del proveedor',
                'verbose_name_plural': 'Productos del proveedor',
                'ordering': ['-fecha_sync'],
                'unique_together': {('proveedor', 'proveedor_product_id')},
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor_order_id', models.CharField(blank=True, max_length=200, verbose_name='ID del pedido en el proveedor')),
                ('estado', models.CharField(choices=[('pendiente_envio', 'Pendiente de envío'), ('enviado', 'Enviado al proveedor'), ('confirmado', 'Confirmado por proveedor'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('error_proveedor', 'Error del proveedor'), ('cancelado', 'Cancelado')], default='pendiente_envio', max_length=30, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (COP)')),
                ('moneda', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('payload_enviado', models.JSONField(blank=True, null=True, verbose_name='Payload enviado')),
                ('respuesta_proveedor', models.JSONField(blank=True, null=True, verbose_name='Respuesta del proveedor')),
                ('intentos', models.PositiveIntegerField(default=0, verbose_name='Intentos de envío')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('pedido_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_proveedor', to='orders.order', verbose_name='Pedido local')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pedido al proveedor',
                'verbose_name_plural': 'Pedidos al proveedor',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('webhook_entrante', 'Webhook entrante'), ('pedido_enviado', 'Pedido enviado'), ('pedido_error', 'Error de pedido'), ('sync_producto', 'Sincronización de producto'), ('sync_stock', 'Cambio de stock'), ('sync_precio', 'Cambio de precio'), ('tracking_update', 'Actualización de tracking'), ('error', 'Error general')], max_length=30, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload')),
                ('respuesta', models.JSONField(blank=True, null=True, verbose_name='Respuesta')),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('rechazado', 'Rechazado')], max_length=20, verbose_name='Estado')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha / hora')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Log del proveedor',
                'verbose_name_plural': 'Logs del proveedor',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrackingProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor_tracking_id', models.CharField(blank=True, max_length=200, verbose_name='ID de tracking en el proveedor')),
                ('numero_guia', models.CharField(blank=True, max_length=200, verbose_name='Número de guía')),
                ('estado_envio', models.CharField(max_length=100, verbose_name='Estado del envío')),
                ('transportadora', models.CharField(blank=True, max_length=200, verbose_name='Transportadora')),
                ('url_tracking', models.URLField(blank=True, verbose_name='URL de seguimiento')),
                ('historial_eventos', models.JSONField(default=list, help_text='Lista cronológica: [{fecha, estado, descripcion, ubicacion}]', verbose_name='Historial de eventos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='proveedores.pedidoproveedor', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Tracking del proveedor',
                'verbose_name_plural': 'Trackings del proveedor',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor_variant_id', models.CharField(max_length=200, verbose_name='ID de variante en el proveedor')),
                ('sku', models.CharField(max_length=200, verbose_name='SKU')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio reportado por el proveedor sin margen.', max_digits=12, verbose_name='Precio base (proveedor)')),
                ('precio_calculado', models.DecimalField(decimal_places=2, help_text='Precio final aplicando la política de precios del proveedor.', max_digits=12, verbose_name='Precio calculado (con margen)')),
                ('stock', models.IntegerField(default=0, help_text='Stock reportado por el proveedor menos el buffer_stock configurado.', verbose_name='Stock disponible (ajustado)')),
                ('atributos', models.JSONField(default=dict, help_text='Ej: {"color": "negro", "talla": "M"}', verbose_name='Atributos')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('agotado', 'Agotado'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('imagen_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='proveedores.productoproveedor', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante del proveedor',
                'verbose_name_plural': 'Variantes del proveedor',
                'unique_together': {('producto', 'proveedor_variant_id')},
            },
        ),
    ]
