# Generated by Django 5.0.4 on 2026-03-20 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_beneficios'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVinculado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_maximo', models.PositiveIntegerField(default=10, help_text='Límite de stock que el cliente verá, sin importar cuánto tenga el proveedor. Fórmula: min(stock_proveedor, stock_maximo)', verbose_name='Stock máximo visible')),
                ('margen_precio_override', models.DecimalField(blank=True, decimal_places=4, help_text='Si se define, sobreescribe la política de precios del proveedor para este producto.', max_digits=5, null=True, verbose_name='Margen de precio (override)')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, el vínculo existe pero no se sincroniza ni afecta al catálogo.', verbose_name='Activo')),
                ('sincronizar', models.BooleanField(default=True, help_text='Si está desactivado, el stock NO se actualiza automáticamente por webhooks.', verbose_name='Sincronización automática')),
                ('stock_calculado', models.IntegerField(default=0, editable=False, verbose_name='Stock calculado (caché)')),
                ('ultimo_recalculo', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último recálculo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_proveedor', to='products.product', verbose_name='Producto del catálogo')),
                ('variante_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='proveedores.varianteproveedor', verbose_name='Variante del proveedor')),
            ],
            options={
                'verbose_name': 'Producto vinculado',
                'verbose_name_plural': 'Productos vinculados',
                'ordering': ['-creado_en'],
                'unique_together': {('variante_proveedor', 'producto_local')},
            },
        ),
    ]
