# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_productovinculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='adapter',
            field=models.CharField(
                choices=[
                    ('rest_generico', 'REST JSON genérico (Bearer + /orders/)'),
                    ('dropi', 'Dropi (payload específico — revisar credenciales)'),
                ],
                default='rest_generico',
                help_text='Define el formato de autenticación y payload al enviar pedidos al proveedor.',
                max_length=32,
                verbose_name='Adaptador de API',
            ),
        ),
    ]
