# Generated by Django 5.0.4 on 2026-03-22 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_local_category_to_supplier_product'),
        ('proveedores', '0005_rename_models_and_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto vinculado', 'verbose_name_plural': 'Productos vinculados'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='supplierorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido al proveedor', 'verbose_name_plural': 'Pedidos al proveedor'},
        ),
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={'ordering': ['-synced_at'], 'verbose_name': 'Producto del proveedor', 'verbose_name_plural': 'Productos del proveedor'},
        ),
        migrations.AlterModelOptions(
            name='suppliertracking',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Tracking del proveedor', 'verbose_name_plural': 'Trackings del proveedor'},
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='local_category',
            field=models.ForeignKey(blank=True, help_text='Categoría de TU catálogo a la que pertenece este producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='products.category', verbose_name='Categoría en tu tienda'),
        ),
        migrations.AlterField(
            model_name='linkedproduct',
            name='calculated_stock',
            field=models.IntegerField(default=0, editable=False, verbose_name='Stock calculado'),
        ),
        migrations.AlterField(
            model_name='linkedproduct',
            name='local_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_proveedor', to='products.product', verbose_name='Producto local'),
        ),
        migrations.AlterField(
            model_name='linkedproduct',
            name='max_stock',
            field=models.PositiveIntegerField(default=10, help_text='Límite de stock que el cliente verá, sin importar cuánto tenga el proveedor. Fórmula: min(stock_proveedor, max_stock)', verbose_name='Stock máximo'),
        ),
        migrations.AlterField(
            model_name='linkedproduct',
            name='price_margin',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Si se define, sobreescribe la política de precios del proveedor para este producto.', max_digits=5, null=True, verbose_name='Margen de precio'),
        ),
        migrations.AlterField(
            model_name='linkedproduct',
            name='sync_enabled',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el stock NO se actualiza automáticamente por webhooks.', verbose_name='Sincronizar'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_days',
            field=models.PositiveIntegerField(default=3, verbose_name='Días de entrega'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='origin_currency',
            field=models.CharField(default='COP', max_length=3, verbose_name='Moneda de origen'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='supplier_order_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID del pedido en proveedor'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='category_name',
            field=models.CharField(blank=True, help_text='Nombre de categoría tal como la define el proveedor (informativo, solo lectura).', max_length=200, verbose_name='Categoría del proveedor'),
        ),
        migrations.AlterField(
            model_name='suppliertracking',
            name='shipping_status',
            field=models.CharField(max_length=100, verbose_name='Estado de envío'),
        ),
        migrations.AlterField(
            model_name='suppliertracking',
            name='supplier_tracking_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID de tracking del proveedor'),
        ),
        migrations.AlterField(
            model_name='suppliertracking',
            name='tracking_url',
            field=models.URLField(blank=True, verbose_name='URL de tracking'),
        ),
        migrations.AlterField(
            model_name='suppliervariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio reportado por el proveedor sin margen.', max_digits=12, verbose_name='Precio base'),
        ),
        migrations.AlterField(
            model_name='suppliervariant',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio final aplicando la política de precios del proveedor.', max_digits=12, verbose_name='Precio calculado'),
        ),
        migrations.AlterField(
            model_name='suppliervariant',
            name='supplier_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='proveedores.supplierproduct', verbose_name='Producto del proveedor'),
        ),
    ]
