# Generated by Django 5.0.4 on 2026-03-21 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_neki_manual_payment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_manual__557d42_idx',
            old_name='ord_manualpay_idx',
        ),
    ]
