# Generated by Django 5.0.4 on 2026-04-01 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_order_payment_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('regret', 'Me arrepentí de la compra'), ('wrong_product', 'Producto diferente al solicitado'), ('defective', 'Producto defectuoso'), ('incomplete', 'Producto incompleto'), ('damaged', 'Producto dañado en transporte'), ('other', 'Otro')], max_length=20, verbose_name='Motivo')),
                ('reason_detail', models.TextField(blank=True, verbose_name='Detalle del motivo')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('reviewing', 'En revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('in_transit', 'En envío (cliente devuelve)'), ('received', 'Recibida'), ('validated', 'Validada'), ('refunded', 'Reembolsada'), ('closed', 'Cerrada')], db_index=True, default='requested', max_length=20, verbose_name='Estado')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Observaciones del cliente')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Observaciones del admin')),
                ('refund_method', models.CharField(blank=True, choices=[('original', 'Método de pago original'), ('store_credit', 'Crédito en tienda'), ('bank_transfer', 'Transferencia bancaria')], max_length=20, verbose_name='Método de reembolso')),
                ('refund_status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Reembolso parcial'), ('full', 'Reembolso total'), ('denied', 'Denegado'), ('processed', 'Procesado')], default='pending', max_length=20, verbose_name='Estado del reembolso')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto reembolsado')),
                ('refund_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reembolso')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_request', to='orders.order', verbose_name='Orden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='returns/evidence/%Y/%m/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='returns.returnrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.CreateModel(
            name='ReturnAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20, verbose_name='Estado anterior')),
                ('to_status', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='returns.returnrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Auditoría de devolución',
                'verbose_name_plural': 'Auditoría de devoluciones',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad a devolver')),
                ('condition', models.CharField(choices=[('unused', 'Sin uso'), ('used', 'Con uso'), ('damaged', 'Dañado')], default='unused', max_length=20, verbose_name='Estado del producto')),
                ('has_original_packaging', models.BooleanField(default=True, verbose_name='Tiene empaque original')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem', verbose_name='Ítem de orden')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Ítem de devolución',
                'verbose_name_plural': 'Ítems de devolución',
                'unique_together': {('return_request', 'order_item')},
            },
        ),
    ]
