# Generated by Django 5.0.4 on 2026-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_return_rejection_types_and_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notas internas (admin)'),
        ),
    ]
