# Generated by Django 5.0.4 on 2026-03-19 20:49

import django.core.validators
import django.db.models.deletion
import products.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock_por_talla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada el'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Clase Font Awesome, ej: fas fa-tshirt', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[products.validators.validate_image_file], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category', verbose_name='Categoría padre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera automáticamente del nombre', unique=True, verbose_name='Identificador URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizada el'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('add', 'Adición'), ('remove', 'Retiro'), ('sale', 'Venta'), ('return', 'Devolución'), ('adjustment', 'Ajuste')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='quantity_change',
            field=models.IntegerField(help_text='Positivo para entradas, negativo para salidas', verbose_name='Cambio de cantidad'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='stock_after',
            field=models.IntegerField(verbose_name='Stock resultante'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='stock_before',
            field=models.IntegerField(verbose_name='Stock anterior'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant', verbose_name='Variante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock mínimo de alerta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descripción SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera automáticamente del nombre', max_length=250, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('out_of_stock', 'Agotado'), ('coming_soon', 'Próximamente')], default='active', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tallas_disponibles',
            field=models.JSONField(blank=True, default=list, help_text='Calculado automáticamente desde stock_por_talla', verbose_name='Tallas disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, verbose_name='Controlar inventario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=8, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[products.validators.validate_image_file], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprobada'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Compra verificada'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizada'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, verbose_name='Código de color (hex)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/', validators=[products.validators.validate_image_file], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(help_text='Ej: Talla M — Fondo Verde', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ajuste al precio base (+/- COP)', max_digits=10, verbose_name='Ajuste de precio'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Talla / Tamaño'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código SKU'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Identificador URL'),
        ),
    ]
