# Generated by Django 5.0.4 on 2026-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_tag_options_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beneficios',
            field=models.JSONField(blank=True, default=list, help_text='Lista de hasta 5 beneficios cortos. Ej: ["Alta resistencia", "Tela ignífuga"]', verbose_name='Beneficios principales'),
        ),
    ]
