# Generated by Django 5.0.4 on 2026-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text='Calculado automáticamente desde stock_by_size', verbose_name='Tallas disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Lista de hasta 5 beneficios cortos. Ej: ["Alta resistencia", "Tela ignífuga"]', verbose_name='Beneficios'),
        ),
    ]
