# Generated by Django 5.0.4 on 2026-04-15 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview_order_productreview_status_reviewevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Use un color hexadecimal # seguido de 6 caracteres (0-9, A-F) o deje en blanco.', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Código de color (hex)'),
        ),
    ]
