# Generated by Django 5.0.4 on 2026-04-15 23:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_proof'),
        ('products', '0009_alter_productvariant_color_hex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user', 'order')},
        ),
    ]
