# Generated by Django 5.0.4 on 2026-03-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loyaltyaccount',
            new_name='loyalty_loy_user_id_170e64_idx',
            old_name='loyalty_acc_user_idx',
        ),
        migrations.RenameIndex(
            model_name='pointtransaction',
            new_name='loyalty_poi_account_af6ce3_idx',
            old_name='loyalty_tx_account_date_idx',
        ),
        migrations.RenameIndex(
            model_name='pointtransaction',
            new_name='loyalty_poi_order_i_c95c75_idx',
            old_name='loyalty_tx_order_idx',
        ),
    ]
