# Generated by Django 5.0.4 on 2026-03-29 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Cuántos pesos COP equivalen a 1 USD. Ej: 4000.00', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tasa USD → COP')),
                ('rate_date', models.DateField(help_text='Fecha en que se estableció esta tasa', verbose_name='Fecha de la tasa')),
                ('notes', models.CharField(blank=True, help_text='Opcional. Ej: "Fuente: Banco de la República"', max_length=255, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-rate_date', '-created_at'],
            },
        ),
    ]
